// flow-typed signature: a09e63913dabd5e814bd7a95ab41c383
// flow-typed version: <<STUB>>/eslint-config-esayemm_v2.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-esayemm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-esayemm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-esayemm/configs/defaults' {
  declare module.exports: any;
}

declare module 'eslint-config-esayemm/configs/ecmascript6' {
  declare module.exports: any;
}

declare module 'eslint-config-esayemm/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-esayemm/configs/defaults.js' {
  declare module.exports: $Exports<'eslint-config-esayemm/configs/defaults'>;
}
declare module 'eslint-config-esayemm/configs/ecmascript6.js' {
  declare module.exports: $Exports<'eslint-config-esayemm/configs/ecmascript6'>;
}
declare module 'eslint-config-esayemm/index' {
  declare module.exports: $Exports<'eslint-config-esayemm'>;
}
declare module 'eslint-config-esayemm/index.js' {
  declare module.exports: $Exports<'eslint-config-esayemm'>;
}
declare module 'eslint-config-esayemm/react.js' {
  declare module.exports: $Exports<'eslint-config-esayemm/react'>;
}
